import { Phrase } from '../types';

export const mockPhrases: Omit<Phrase, 'id'>[] = [
  {
    phrase: "Cut corners",
    meaning: "Sifatni pasaytirgan holda ishni tezroq yoki arzonroq qilish.",
    uzbekEquivalent: "Qisqa yo'l izlamoq / Sifatga e'tibor bermaslik.",
    example: "The contractor cut corners on the building materials, and now there are serious problems.",
    exampleTranslation: "Pudratchi qurilish materiallarida sifatga e'tibor bermadi, endi jiddiy muammolar bor.",
    speakingIdea: "I never cut corners when it comes to my health — I always buy quality food.",
    speakingIdeaTranslation: "Sog'ligim haqida gap ketganda hech qachon sifatga e'tibor bermaslik yo'lini tutmayman — har doim sifatli ovqat sotib olaman.",
    collocations: ["cut corners on", "tempted to cut corners", "never cut corners"],
    difficulty: "intermediate",
    category: "Work & Quality"
  },
  {
    phrase: "Go the extra mile",
    meaning: "Kutilgandan ko'proq harakat qilish, qo'shimcha sa'y-harakat sarflash.",
    uzbekEquivalent: "Qo'shimcha harakat qilmoq / Tashabbus ko'rsatmoq.",
    example: "She always goes the extra mile for her clients, which is why they keep coming back.",
    exampleTranslation: "U har doim mijozlari uchun qo'shimcha harakat qiladi, shuning uchun ular qaytib kelishadi.",
    speakingIdea: "I try to go the extra mile in my studies by reading beyond what the teacher assigns.",
    speakingIdeaTranslation: "O'qishda o'qituvchi berganidan tashqari qo'shimcha o'qib, ko'proq harakat qilishga harakat qilaman.",
    collocations: ["go the extra mile for", "willing to go the extra mile", "always goes the extra mile"],
    difficulty: "intermediate",
    category: "Work & Effort"
  },
  {
    phrase: "Sit on the fence",
    meaning: "Ikki tomondan birini tanlamasdan neytral pozitsiyada qolish.",
    uzbekEquivalent: "Betaraf turmoq / Ikki o'rtada qolmoq.",
    example: "You can't sit on the fence forever — you need to make a decision.",
    exampleTranslation: "Abadiy betaraf tura olmaysiz — qaror qabul qilishingiz kerak.",
    speakingIdea: "When my friends argue, I usually sit on the fence rather than take sides.",
    speakingIdeaTranslation: "Do'stlarim tortishganda, odatda tomonlardan birini olmasdan betaraf turaman.",
    collocations: ["sit on the fence", "stop sitting on the fence", "tend to sit on the fence"],
    difficulty: "advanced",
    category: "Decision Making"
  },
  {
    phrase: "In the same boat",
    meaning: "Bir xil qiyin vaziyatda bo'lish.",
    uzbekEquivalent: "Bir qozon ichida qaynash / Bir xil ahvolda bo'lish.",
    example: "Don't worry, we're all in the same boat when it comes to the deadline.",
    exampleTranslation: "Xavotir olmang, muddat masalasida barchamiz bir xil ahvoldamiz.",
    speakingIdea: "When I struggled with online classes, I realized my classmates were in the same boat.",
    speakingIdeaTranslation: "Onlayn darslar bilan qiynalganimda, sinfdoshlarim ham bir xil ahvolda ekanini angladim.",
    collocations: ["in the same boat as", "we're all in the same boat", "find yourself in the same boat"],
    difficulty: "beginner",
    category: "Relationships"
  },
  {
    phrase: "Bite the dust",
    meaning: "Muvaffaqiyatsizlikka uchramoq yoki to'xtab qolmoq.",
    uzbekEquivalent: "Yer tishlash / Mag'lubiyatga uchramoq.",
    example: "Several small businesses bit the dust during the economic crisis.",
    exampleTranslation: "Iqtisodiy inqiroz davrida bir nechta kichik bizneslar muvaffaqiyatsizlikka uchradi.",
    speakingIdea: "My first attempt at learning guitar bit the dust after just two weeks.",
    speakingIdeaTranslation: "Gitara o'rganishga birinchi urinishim atigi ikki haftadan keyin barbod bo'ldi.",
    collocations: ["bit the dust", "watch something bite the dust", "finally bit the dust"],
    difficulty: "intermediate",
    category: "Failure"
  },
  {
    phrase: "Take with a grain of salt",
    meaning: "Biror ma'lumotni to'liq ishonmasdan, shubha bilan qabul qilish.",
    uzbekEquivalent: "Shubha bilan qabul qilmoq / So'ziga to'liq ishonmaslik.",
    example: "Take his advice with a grain of salt — he's not always right.",
    exampleTranslation: "Uning maslahatini shubha bilan qabul qiling — u har doim ham to'g'ri emas.",
    speakingIdea: "I take social media health tips with a grain of salt and consult a doctor instead.",
    speakingIdeaTranslation: "Ijtimoiy tarmoqlardagi sog'liq maslahatlarini shubha bilan qabul qilaman va buning o'rniga shifokorga murojaat qilaman.",
    collocations: ["take it with a grain of salt", "should be taken with a grain of salt", "take everything with a grain of salt"],
    difficulty: "advanced",
    category: "Critical Thinking"
  },
  {
    phrase: "Burn bridges",
    meaning: "Birov bilan munosabatni butunlay buzib, qaytib bo'lmaydigan holatga keltirish.",
    uzbekEquivalent: "Ko'prikni yoqib yubormoq / Munosabatni butunlay uzmoq.",
    example: "Don't burn bridges with your colleagues — you never know when you'll need them.",
    exampleTranslation: "Hamkasblaringiz bilan munosabatni buzib qo'ymang — ularga qachon muhtoj bo'lishingizni hech qachon bilmaysiz.",
    speakingIdea: "Even when I leave a job, I try not to burn bridges because the world is small.",
    speakingIdeaTranslation: "Ishdan ketganda ham, ko'prikni yoqib yubormashga harakat qilaman, chunki dunyo kichkina.",
    collocations: ["burn bridges with", "avoid burning bridges", "burned his bridges"],
    difficulty: "intermediate",
    category: "Relationships"
  },
  {
    phrase: "Cut to the chase",
    meaning: "Keraksiz so'zlarni tashlab, asosiy mavzuga o'tish.",
    uzbekEquivalent: "Gapning lo'ndasini aytmoq / Asosga o'tmoq.",
    example: "Let's cut to the chase — how much does it actually cost?",
    exampleTranslation: "Gapning lo'ndasiga o'taylik — bu aslida qanchaga tushadi?",
    speakingIdea: "In presentations, I always try to cut to the chase so I don't waste people's time.",
    speakingIdeaTranslation: "Taqdimotlarda odamlarning vaqtini behuda sarflamaslik uchun har doim asosga o'tishga harakat qilaman.",
    collocations: ["cut to the chase", "let's cut to the chase", "cut to the chase and tell me"],
    difficulty: "intermediate",
    category: "Communication"
  },
  {
    phrase: "Get the ball rolling",
    meaning: "Biror ishni boshlash, jarayonni ishga tushirish.",
    uzbekEquivalent: "Ishga tushirmoq / Boshlab yubormoq.",
    example: "Someone needs to get the ball rolling on this project before the deadline.",
    exampleTranslation: "Muddat kelishidan oldin kimdir bu loyihani boshlab yuborishi kerak.",
    speakingIdea: "I got the ball rolling on our team project by creating the initial outline.",
    speakingIdeaTranslation: "Dastlabki rejani tuzib, jamoa loyihamizni boshlab yubordim.",
    collocations: ["get the ball rolling on", "got the ball rolling", "help get the ball rolling"],
    difficulty: "intermediate",
    category: "Productivity"
  },
  {
    phrase: "Read between the lines",
    meaning: "Ochiq aytilmagan yashirin ma'noni tushunish.",
    uzbekEquivalent: "Satrlar orasini o'qimoq / Yashirin ma'noni anglamoq.",
    example: "She said she was 'fine', but reading between the lines, I could tell she was upset.",
    exampleTranslation: "U 'yaxshi' dedi, lekin yashirin ma'noni anglasam, u xafa ekanini bilib oldim.",
    speakingIdea: "When I read news articles, I always try to read between the lines to understand the full picture.",
    speakingIdeaTranslation: "Yangiliklar maqolalarini o'qiganimda, to'liq rasmni tushunish uchun har doim yashirin ma'noni anglashga harakat qilaman.",
    collocations: ["read between the lines", "learn to read between the lines", "reading between the lines"],
    difficulty: "advanced",
    category: "Critical Thinking"
  },
  {
    phrase: "Push the envelope",
    meaning: "Mumkin bo'lgan chegaralarni kengaytirish, yangi narsalarni sinab ko'rish.",
    uzbekEquivalent: "Chegaralarni kengaytirmoq / Yangilik qilmoq.",
    example: "The designer always pushes the envelope with unconventional ideas.",
    exampleTranslation: "Dizayner har doim g'ayriodatiy g'oyalar bilan chegaralarni kengaytiradi.",
    speakingIdea: "I like to push the envelope in my writing by experimenting with different styles.",
    speakingIdeaTranslation: "Yozuvimda turli uslublarni sinab ko'rib, chegaralarni kengaytirishni yaxshi ko'raman.",
    collocations: ["push the envelope", "always pushes the envelope", "push the envelope on"],
    difficulty: "advanced",
    category: "Innovation"
  },
  {
    phrase: "Bite the hand that feeds you",
    meaning: "O'zingga yordam bergan odamga qarshi chiqish.",
    uzbekEquivalent: "Yaxshilikka yomonlik qilmoq.",
    example: "Criticizing your own employer publicly is biting the hand that feeds you.",
    exampleTranslation: "Ish beruvchingizni ommaviy tanqid qilish yaxshilikka yomonlik qilish demakdir.",
    speakingIdea: "I would never bite the hand that feeds me by speaking badly about my mentors.",
    speakingIdeaTranslation: "Murabbiylarim haqida yomon gapirish orqali yaxshilikka yomonlik qilmayman.",
    collocations: ["bite the hand that feeds you", "don't bite the hand", "biting the hand that feeds"],
    difficulty: "advanced",
    category: "Relationships"
  },
  {
    phrase: "Give the benefit of the doubt",
    meaning: "Biror kishini dalil yo'q bo'lganda yaxshi niyatli deb qabul qilish.",
    uzbekEquivalent: "Yaxshi niyatli deb qabul qilmoq / Ishonch bermoq.",
    example: "He was late, but I gave him the benefit of the doubt since he's usually reliable.",
    exampleTranslation: "U kech qoldi, lekin odatda ishonchli bo'lgani uchun uni yaxshi niyatli deb qabul qildim.",
    speakingIdea: "When someone makes a mistake, I prefer to give them the benefit of the doubt.",
    speakingIdeaTranslation: "Kimdir xato qilganda, uni yaxshi niyatli deb qabul qilishni afzal ko'raman.",
    collocations: ["give the benefit of the doubt", "deserve the benefit of the doubt", "gave him the benefit of the doubt"],
    difficulty: "advanced",
    category: "Relationships"
  },
  {
    phrase: "Keep a low profile",
    meaning: "E'tiborni o'ziga jalb qilmasdan xotirjam yashash.",
    uzbekEquivalent: "Ko'zga ko'rinmaslik / Jim yurmoq.",
    example: "After the controversy, the CEO decided to keep a low profile for a few months.",
    exampleTranslation: "Janjal keyin ijrochi direktor bir necha oy ko'zga ko'rinmaslikka qaror qildi.",
    speakingIdea: "I prefer to keep a low profile at big social events rather than being the center of attention.",
    speakingIdeaTranslation: "Katta ijtimoiy tadbirlarda diqqat markazida bo'lishdan ko'ra, ko'zga ko'rinmaslikni afzal ko'raman.",
    collocations: ["keep a low profile", "decided to keep a low profile", "try to keep a low profile"],
    difficulty: "intermediate",
    category: "Social"
  },
  {
    phrase: "Face the music",
    meaning: "O'z xatti-harakatlari uchun javobgarlikni qabul qilish.",
    uzbekEquivalent: "Javob bermoq / Oqibatiga dosh bermoq.",
    example: "After missing so many deadlines, he finally had to face the music with his manager.",
    exampleTranslation: "Ko'p muddatlarni o'tkazib yuborgandan keyin, u nihoyat menejeri oldida javob berishi kerak bo'ldi.",
    speakingIdea: "When I make a mistake, I believe in facing the music rather than making excuses.",
    speakingIdeaTranslation: "Xato qilganimda, bahona o'ylab topishdan ko'ra javob berishga ishonaman.",
    collocations: ["face the music", "time to face the music", "had to face the music"],
    difficulty: "intermediate",
    category: "Responsibility"
  },
  {
    phrase: "Jump on the bandwagon",
    meaning: "Mashhur bo'lgan narsaga shunchaki boshqalar qilgani uchun qo'shilish.",
    uzbekEquivalent: "Oqimga ergashmoq / Modaga ergashmoq.",
    example: "Everyone jumped on the bandwagon when the new fitness trend went viral.",
    exampleTranslation: "Yangi fitness trendi mashhur bo'lganda, hamma oqimga ergashdi.",
    speakingIdea: "I try not to jump on the bandwagon with every new technology trend without researching it first.",
    speakingIdeaTranslation: "Har yangi texnologiya trendiga avval o'rganib ko'rmasdan ergashmaslikka harakat qilaman.",
    collocations: ["jump on the bandwagon", "jumped on the bandwagon", "don't just jump on the bandwagon"],
    difficulty: "intermediate",
    category: "Social"
  },
  {
    phrase: "Turn a blind eye",
    meaning: "Biror narsani ko'ra turib ko'rmaslikka olish.",
    uzbekEquivalent: "Ko'zini yummoq / Bilmaslikka olmoq.",
    example: "The manager turned a blind eye to the team's minor rule violations.",
    exampleTranslation: "Menejer jamoa a'zolarining mayda qoidabuzarliklariga ko'zini yumdi.",
    speakingIdea: "It's hard to turn a blind eye when you see someone being treated unfairly.",
    speakingIdeaTranslation: "Kimning adolatsizlikka uchraganini ko'rganda, ko'zingni yumish qiyin.",
    collocations: ["turn a blind eye to", "can't turn a blind eye", "turned a blind eye"],
    difficulty: "advanced",
    category: "Ethics"
  },
  {
    phrase: "Throw someone under the bus",
    meaning: "O'zini himoya qilish uchun boshqani aybdor qilib ko'rsatish.",
    uzbekEquivalent: "Boshqani qurbon qilmoq / Boshqaga to'nkash.",
    example: "When the project failed, he threw his teammate under the bus to save himself.",
    exampleTranslation: "Loyiha muvaffaqiyatsiz bo'lganda, u o'zini qutqarish uchun jamoadoshini qurbon qildi.",
    speakingIdea: "I would never throw a colleague under the bus — teamwork means supporting each other.",
    speakingIdeaTranslation: "Hamkorni hech qachon qurbon qilmayman — jamoa ishi bir-birini qo'llab-quvvatlash demak.",
    collocations: ["throw someone under the bus", "threw me under the bus", "don't throw people under the bus"],
    difficulty: "advanced",
    category: "Work & Ethics"
  },
  {
    phrase: "Hit the sack",
    meaning: "Uxlash uchun yotmoq.",
    uzbekEquivalent: "Uxlashga yotmoq / Ko'rpa-to'shakka kirmoq.",
    example: "I'm exhausted — I need to hit the sack as soon as I get home.",
    exampleTranslation: "Juda charchadim — uyga borganimdan keyin darhol uxlashim kerak.",
    speakingIdea: "I usually hit the sack around 10 PM to make sure I get enough sleep.",
    speakingIdeaTranslation: "Yetarli uxlash uchun odatda kechki soat 10 da uxlashga yotaman.",
    collocations: ["hit the sack", "time to hit the sack", "ready to hit the sack"],
    difficulty: "beginner",
    category: "Daily Life"
  },
  {
    phrase: "Get out of your comfort zone",
    meaning: "O'zingiz uchun qulay bo'lmagan yangi narsalarni sinab ko'rish.",
    uzbekEquivalent: "Qulaylik zonasidan chiqmoq / O'zini sinab ko'rmoq.",
    example: "Studying abroad really forced me to get out of my comfort zone.",
    exampleTranslation: "Chet elda o'qish meni haqiqatan ham qulaylik zonasidan chiqishga majbur qildi.",
    speakingIdea: "I try to get out of my comfort zone every month by learning a new skill.",
    speakingIdeaTranslation: "Har oy yangi ko'nikma o'rganib, qulaylik zonasidan chiqishga harakat qilaman.",
    collocations: ["get out of your comfort zone", "step outside your comfort zone", "push yourself out of your comfort zone"],
    difficulty: "beginner",
    category: "Personal Growth"
  },
  {
    phrase: "Beat around the bush",
    meaning: "Asosiy mavzudan qochib, gapni cho'zish.",
    uzbekEquivalent: "Gapni aylantirib o'tirmoq.",
    example: "Stop beating around the bush and tell me what actually happened.",
    exampleTranslation: "Gapni aylantirib o'tirmay, aslida nima bo'lganini ayt.",
    speakingIdea: "I hate when people beat around the bush instead of saying what they mean.",
    speakingIdeaTranslation: "Odamlar o'z fikrini to'g'ri aytmasdan gapni aylantirib o'tirishini yoqtirmayman.",
    collocations: ["stop beating around the bush", "always beats around the bush", "don't beat around the bush"],
    difficulty: "intermediate",
    category: "Communication"
  },
  {
    phrase: "Kill two birds with one stone",
    meaning: "Bir harakatda ikki muammoni hal qilish.",
    uzbekEquivalent: "Bir o'qda ikki quyonni urmoq.",
    example: "I went to the gym near my office — killed two birds with one stone.",
    exampleTranslation: "Ofisim yaqinidagi sport zalga bordim — bir o'qda ikki quyonni urdim.",
    speakingIdea: "I try to kill two birds with one stone by listening to podcasts while commuting.",
    speakingIdeaTranslation: "Ishga ketayotganda podcast eshitib, bir vaqtda ikki ishni bitta qilishga harakat qilaman.",
    collocations: ["kill two birds with one stone", "trying to kill two birds", "perfect way to kill two birds"],
    difficulty: "beginner",
    category: "Productivity"
  },
  {
    phrase: "On the fence",
    meaning: "Ikki o'rt bo'lish, qaror qila olmaslik.",
    uzbekEquivalent: "Ikkilanmoq / Bir qarorga kela olmaslik.",
    example: "I'm still on the fence about whether to accept the job offer.",
    exampleTranslation: "Ish taklifini qabul qilish yoki qilmaslik haqida hali ikkilanib turibman.",
    speakingIdea: "I was on the fence about studying abroad, but finally decided to go.",
    speakingIdeaTranslation: "Chet elda o'qish haqida ikkilandim, lekin oxir-oqibat borishga qaror qildim.",
    collocations: ["still on the fence", "sitting on the fence", "on the fence about"],
    difficulty: "intermediate",
    category: "Decision Making"
  },
  {
    phrase: "Bite the hand that feeds you",
    meaning: "Sizga yordam bergan odamga zarar yetkazish.",
    uzbekEquivalent: "Yaxshilikka yomonlik qilmoq.",
    example: "He criticized his own company publicly — that's biting the hand that feeds you.",
    exampleTranslation: "U o'z kompaniyasini ommaviy ravishda tanqid qildi — bu yaxshilikka yomonlik qilish.",
    speakingIdea: "I would never bite the hand that feeds me by betraying someone who helped me.",
    speakingIdeaTranslation: "Menga yordam bergan odonga xiyonat qilib, yaxshilikka yomonlik qilmayman.",
    collocations: ["biting the hand that feeds you", "never bite the hand", "don't bite the hand that feeds you"],
    difficulty: "advanced",
    category: "Relationships"
  },
  {
    phrase: "The tip of the iceberg",
    meaning: "Katta muammoning yoki vaziyatning faqat ko'rinadigan kichik qismi.",
    uzbekEquivalent: "Aysbergning uchi / Ko'rinadigan qismi.",
    example: "The scandal we heard about is just the tip of the iceberg.",
    exampleTranslation: "Eshitgan janjalimiz faqat aysbergning uchi xolos.",
    speakingIdea: "What I told you about my problems is just the tip of the iceberg.",
    speakingIdeaTranslation: "Muammolarim haqida aytganlarim faqat aysbergning uchi edi.",
    collocations: ["just the tip of the iceberg", "only the tip of the iceberg", "tip of the iceberg when it comes to"],
    difficulty: "intermediate",
    category: "Problem Solving"
  },
  {
    phrase: "Miss the boat",
    meaning: "Imkoniyatni o'tkazib yuborish, kech qolish.",
    uzbekEquivalent: "Kemani o'tkazib yubormoq / Imkoniyatni qo'ldan bermoq.",
    example: "He missed the boat on investing in that startup — it's worth millions now.",
    exampleTranslation: "U o'sha startapga sarmoya kiritish imkoniyatini o'tkazib yubordi — u endi millionlarga arziydi.",
    speakingIdea: "I missed the boat on learning programming early, so now I'm starting late.",
    speakingIdeaTranslation: "Dasturlashni erta o'rganish imkoniyatini o'tkazib yubordim, shuning uchun hozir kech boshlamoqdaman.",
    collocations: ["missed the boat on", "don't miss the boat", "afraid of missing the boat"],
    difficulty: "intermediate",
    category: "Opportunities"
  },
  {
    phrase: "Bite your tongue",
    meaning: "Gapirmoqchi bo'lgan narsangni aytmaslik, o'zingni tiyish.",
    uzbekEquivalent: "Tilingni tishlab olmoq / O'zingni tiymoq.",
    example: "I had to bite my tongue during the meeting not to say something rude.",
    exampleTranslation: "Yig'ilishda qo'pol narsa aytib qo'ymaslik uchun tilingni tishlab olishim kerak bo'ldi.",
    speakingIdea: "Sometimes I have to bite my tongue when I disagree with my boss.",
    speakingIdeaTranslation: "Ba'zida boshliqim bilan kelishmaganda tilingni tishlab olishim kerak bo'ladi.",
    collocations: ["bite your tongue", "had to bite my tongue", "biting my tongue"],
    difficulty: "intermediate",
    category: "Communication"
  },
  {
    phrase: "Wear your heart on your sleeve",
    meaning: "His-tuyg'ularingizni yashirmasdan ochiqchasiga ko'rsatish.",
    uzbekEquivalent: "Ko'nglini ko'z-ko'z qilmoq / His-tuyg'ularini yashirmaslik.",
    example: "She wears her heart on her sleeve — you always know exactly how she feels.",
    exampleTranslation: "U his-tuyg'ularini yashirmaydi — uning kayfiyatini har doim bilsa bo'ladi.",
    speakingIdea: "I tend to wear my heart on my sleeve, which makes me easy to read.",
    speakingIdeaTranslation: "Men his-tuyg'ularimni yashirmayman, shuning uchun odamlar meni osongina tushunadi.",
    collocations: ["wears her heart on her sleeve", "wear your heart on your sleeve", "tends to wear heart on sleeve"],
    difficulty: "advanced",
    category: "Emotions"
  },
  {
    phrase: "Pull someone's leg",
    meaning: "Biror kishini hazil uchun aldash yoki qochiriq qilish.",
    uzbekEquivalent: "Biror kishini mazax qilmoq / Hazillashib aldamoq.",
    example: "Are you serious, or are you just pulling my leg?",
    exampleTranslation: "Jiddiy gapyapsanmi, yoki shunchaki hazillashyapsanmi?",
    speakingIdea: "My friends are always pulling my leg about how seriously I take my studies.",
    speakingIdeaTranslation: "Do'stlarim darslarimga juda jiddiy munosabatda bo'lishim haqida doim hazillashadi.",
    collocations: ["pulling my leg", "just pulling your leg", "stop pulling my leg"],
    difficulty: "beginner",
    category: "Humor"
  },
  {
    phrase: "Get out of hand",
    meaning: "Vaziyat nazoratdan chiqib ketish.",
    uzbekEquivalent: "Qo'ldan ketmoq / Nazoratdan chiqmoq.",
    example: "The argument got out of hand and everyone started shouting.",
    exampleTranslation: "Bahs nazoratdan chiqib ketdi va hamma qichqira boshladi.",
    speakingIdea: "I realized my spending was getting out of hand when I checked my bank account.",
    speakingIdeaTranslation: "Bank hisobimni tekshirganimda, xarajatlarim nazoratdan chiqqanini angladim.",
    collocations: ["getting out of hand", "got out of hand", "before it gets out of hand"],
    difficulty: "beginner",
    category: "Control"
  },
  {
    phrase: "Burn the midnight oil",
    meaning: "Kechasi bilan uxlamasdan ishlash yoki dars qilish.",
    uzbekEquivalent: "Tunni tongga ulash.",
    example: "I have a big exam tomorrow, so I'll be burning the midnight oil tonight.",
    exampleTranslation: "Ertaga katta imtihonimiz bor, shuning uchun bugun tuni bilan dars qilaman.",
    speakingIdea: "Sometimes I burn the midnight oil when I work on personal projects.",
    speakingIdeaTranslation: "Ba'zida shaxsiy loyihalarim ustida ishlaganda tun bilan ishlab chiqaman.",
    collocations: ["burn the midnight oil for", "constantly burning the midnight oil", "had to burn the midnight oil"],
    difficulty: "intermediate",
    category: "Work & Study"
  },
  {
    phrase: "Hit the nail on the head",
    meaning: "Biror narsani to'g'ri va aniq aytish yoki bajarish.",
    uzbekEquivalent: "Mil boshiga urmoq / To'g'ri ta'riflash.",
    example: "You hit the nail on the head when you said the project needed more planning.",
    exampleTranslation: "Loyiha ko'proq rejalashtirish kerakligini aytganingizda, to'g'ri ta'rifladingiz.",
    speakingIdea: "My teacher hit the nail on the head when she explained why I kept making the same mistake.",
    speakingIdeaTranslation: "O'qituvchim nima uchun bir xil xatoni takrorlab kelayotganimni tushuntirganda, to'g'ri ta'rifladi.",
    collocations: ["really hit the nail on the head", "hit the nail on the head with", "you've hit the nail on the head"],
    difficulty: "intermediate",
    category: "Communication"
  },
  {
    phrase: "Break the ice",
    meaning: "Tanish bo'lmagan odamlar bilan muloqotni boshlash uchun biror qiziqarli narsa qilish.",
    uzbekEquivalent: "Muloqotni osonlashtirish / Ko'ngilni ochish.",
    example: "He told a funny joke to break the ice at the beginning of the meeting.",
    exampleTranslation: "U yig'ilish boshida muloqotni osonlashtirish uchun kulgili hazil aytdi.",
    speakingIdea: "When I meet new people, I usually ask about their hobbies to break the ice.",
    speakingIdeaTranslation: "Yangi odamlar bilan tanishganda, odatda muloqotni boshlash uchun ularning qiziqishlari haqida so'rayman.",
    collocations: ["break the ice with", "something to break the ice", "tried to break the ice"],
    difficulty: "beginner",
    category: "Social"
  },
  {
    phrase: "Bite the bullet",
    meaning: "Qiyin yoki og'riqli vaziyatni sabr bilan qabul qilish.",
    uzbekEquivalent: "Tishingni tishingga qo'y / Azobga chida.",
    example: "I hate going to the dentist, but I decided to bite the bullet and make an appointment.",
    exampleTranslation: "Men tish shifokoriga borishni yoqtirmayman, lekin azobga chidam va qabulga yozdirdim.",
    speakingIdea: "Sometimes you just have to bite the bullet and do the things you've been avoiding.",
    speakingIdeaTranslation: "Ba'zida shunchaki azobga chidab, qochib yurgan narsalarni qilish kerak bo'ladi.",
    collocations: ["just bite the bullet", "had to bite the bullet", "bite the bullet and do"],
    difficulty: "intermediate",
    category: "Attitude"
  },
  {
    phrase: "Under the weather",
    meaning: "Kasal yoki yomon his qilish.",
    uzbekEquivalent: "Kasalroq bo'lish / Ahvoli yaxshi emas.",
    example: "I'm feeling a bit under the weather today, so I might stay home.",
    exampleTranslation: "Bugun o'zimni yaxshi his qilmayapman, shuning uchun uyda qolishim mumkin.",
    speakingIdea: "When I'm under the weather, I like to drink hot tea and rest all day.",
    speakingIdeaTranslation: "Ahvolim yaxshi bo'lmaganda, issiq choy ichib, kun bo'yi dam olishni yaxshi ko'raman.",
    collocations: ["feeling under the weather", "a bit under the weather", "still under the weather"],
    difficulty: "beginner",
    category: "Health"
  },
  {
    phrase: "Spill the beans",
    meaning: "Yashirin sirni yoki ma'lumotni beixtiyor oshkor qilish.",
    uzbekEquivalent: "Sirni fosh qilish / Og'zingdan chiqarib yuborish.",
    example: "Don't spill the beans about the surprise party — it's a secret!",
    exampleTranslation: "Kutilmagan ziyofat haqida hech kimga aytma — bu sir!",
    speakingIdea: "I accidentally spilled the beans about my friend's promotion before she could announce it herself.",
    speakingIdeaTranslation: "Do'stimning ko'tarilishi haqida u o'zi e'lon qilishidan oldin tasodifan aytib qo'ydim.",
    collocations: ["spill the beans about", "accidentally spilled the beans", "don't spill the beans"],
    difficulty: "beginner",
    category: "Communication"
  },
  {
    phrase: "The ball is in your court",
    meaning: "Qaror qabul qilish navbati sizda.",
    uzbekEquivalent: "Qaror sening qo'lingda / Navbat senda.",
    example: "I've made my offer — the ball is in your court now.",
    exampleTranslation: "Men taklifimni bildirdim — endi qaror sening qo'lingda.",
    speakingIdea: "After I sent the job application, the ball was in their court to decide.",
    speakingIdeaTranslation: "Ish arzonini yuborgandan keyin, qaror qilish ularning navbati edi.",
    collocations: ["the ball is in your court now", "left the ball in their court", "ball is in your court to decide"],
    difficulty: "intermediate",
    category: "Decision Making"
  },
  {
    phrase: "Once in a blue moon",
    meaning: "Juda kamdan-kam hollarda, deyarli hech qachon.",
    uzbekEquivalent: "Kamdan-kam / Nadir holda.",
    example: "We only get snow in this city once in a blue moon.",
    exampleTranslation: "Bu shaharda qor juda kamdan-kam yog'adi.",
    speakingIdea: "Once in a blue moon, I treat myself to an expensive restaurant dinner.",
    speakingIdeaTranslation: "Kamdan-kam hollarda o'zimni qimmat restoranda kechki ovqat bilan siylaman.",
    collocations: ["once in a blue moon", "happens once in a blue moon", "only once in a blue moon"],
    difficulty: "beginner",
    category: "Time & Frequency"
  },
  {
    phrase: "Bite off more than you can chew",
    meaning: "O'z imkoniyatidan ko'ra ko'proq ish olish.",
    uzbekEquivalent: "Ko'zingni og'zingga qarab och.",
    example: "He bit off more than he could chew by taking three jobs at the same time.",
    exampleTranslation: "U bir vaqtning o'zida uchta ish olish bilan o'z imkoniyatidan ko'proq ish olib qo'ydi.",
    speakingIdea: "I bit off more than I could chew when I agreed to help organize the whole conference alone.",
    speakingIdeaTranslation: "Butun konferentsiyani yolg'iz uyushtirish uchun rozi bo'lganimda, o'z imkoniyatimdan ko'proq ish olib qo'ydim.",
    collocations: ["bit off more than I could chew", "don't bite off more than", "risk biting off more than"],
    difficulty: "intermediate",
    category: "Work & Study"
  },
  {
    phrase: "Hit the ground running",
    meaning: "Biror ishni boshida energiya va samaradorlik bilan boshlash.",
    uzbekEquivalent: "Birdaniga tez va samarali ishga kirishish.",
    example: "The new manager hit the ground running and solved several issues on her first day.",
    exampleTranslation: "Yangi menejer birinchi kunidayoq bir necha muammoni hal qilib, samarali ishga kirdi.",
    speakingIdea: "I want to hit the ground running with my new language learning routine.",
    speakingIdeaTranslation: "Yangi til o'rganish tartibimni tez va samarali boshlashni xohlayman.",
    collocations: ["hit the ground running with", "really hit the ground running", "need to hit the ground running"],
    difficulty: "advanced",
    category: "Work & Study"
  },
  {
    phrase: "Let the cat out of the bag",
    meaning: "Yashirin sirni tasodifan oshkor qilish.",
    uzbekEquivalent: "Sirni fosh etib qo'yish.",
    example: "She let the cat out of the bag when she mentioned the surprise birthday party.",
    exampleTranslation: "U kutilmagan tug'ilgan kun ziyofatini tilga olganda sirni fosh etib qo'ydi.",
    speakingIdea: "I almost let the cat out of the bag about the gift we were planning.",
    speakingIdeaTranslation: "Rejalashtirayotgan sovg'amiz haqida sirni deyarli oshkor qilib qo'ydim.",
    collocations: ["let the cat out of the bag about", "accidentally let the cat out", "nearly let the cat out of the bag"],
    difficulty: "beginner",
    category: "Communication"
  },
  {
    phrase: "Throw in the towel",
    meaning: "Biror narsadan voz kechish yoki taslim bo'lish.",
    uzbekEquivalent: "Taslim bo'lish / Qo'l siltash.",
    example: "After years of trying, he finally threw in the towel and changed careers.",
    exampleTranslation: "Yillab harakat qilganidan so'ng, u nihoyat taslim bo'lib, kasb almashtirdi.",
    speakingIdea: "No matter how hard it gets, I refuse to throw in the towel on my dreams.",
    speakingIdeaTranslation: "Qanchalik qiyin bo'lmasin, orzularimdan voz kechishdan bosh tortaman.",
    collocations: ["throw in the towel on", "ready to throw in the towel", "refuse to throw in the towel"],
    difficulty: "intermediate",
    category: "Attitude"
  },
  {
    phrase: "See eye to eye",
    meaning: "Biror masalada kimdir bilan to'liq kelishish.",
    uzbekEquivalent: "Ko'z ko'zga tushmoq / Bir fikrda bo'lmoq.",
    example: "We don't always see eye to eye, but we respect each other's opinions.",
    exampleTranslation: "Biz har doim ham bir fikrda bo'lmaymiz, lekin bir-birimizning fikrlarimizga hurmat qilamiz.",
    speakingIdea: "My brother and I rarely see eye to eye on political topics.",
    speakingIdeaTranslation: "Akam bilan men siyosiy masalalarda kamdan-kam hollarda bir fikrda bo'lamiz.",
    collocations: ["see eye to eye on", "rarely see eye to eye", "don't see eye to eye"],
    difficulty: "beginner",
    category: "Relationships"
  },
  {
    phrase: "Barking up the wrong tree",
    meaning: "Noto'g'ri yo'nalishda izlash yoki noto'g'ri odamni aybdor deb hisoblash.",
    uzbekEquivalent: "Noto'g'ri joydan izlamoq.",
    example: "If you think I took your notebook, you're barking up the wrong tree.",
    exampleTranslation: "Agar daftaringizni men olgan deb o'ylasangiz, noto'g'ri joydan izlayapsiz.",
    speakingIdea: "The police were barking up the wrong tree when they first investigated the case.",
    speakingIdeaTranslation: "Politsiya dastlab ishni tekshirganda noto'g'ri yo'nalishda izladi.",
    collocations: ["barking up the wrong tree", "you're barking up the wrong tree", "were barking up the wrong tree"],
    difficulty: "advanced",
    category: "Problem Solving"
  },
  {
    phrase: "Cost an arm and a leg",
    meaning: "Juda qimmat bo'lish.",
    uzbekEquivalent: "Juda qimmat turmoq / Ko'z chiqarmoq.",
    example: "That new smartphone costs an arm and a leg, but everyone wants one.",
    exampleTranslation: "O'sha yangi smartfon juda qimmat, lekin hamma uni xohlaydi.",
    speakingIdea: "Traveling to Europe cost me an arm and a leg, but it was worth every penny.",
    speakingIdeaTranslation: "Evropaga sayohat qilish juda qimmga tushdi, lekin har bir tiyiniga arzidi.",
    collocations: ["cost an arm and a leg", "costs an arm and a leg", "it cost me an arm and a leg"],
    difficulty: "beginner",
    category: "Money"
  }
];
