import { Phrase } from '../types';

export const mockPhrases: Omit<Phrase, 'id'>[] = [
  {
    phrase: "Burn the midnight oil",
    meaning: "Kechasi bilan uxlamasdan ishlash yoki dars qilish.",
    uzbekEquivalent: "Tunni tongga ulash.",
    example: "I have a big exam tomorrow, so I'll be burning the midnight oil tonight.",
    exampleTranslation: "Ertaga katta imtihonimiz bor, shuning uchun bugun tuni bilan dars qilaman.",
    speakingIdea: "Sometimes I burn the midnight oil when I work on personal projects.",
    speakingIdeaTranslation: "Ba'zida shaxsiy loyihalarim ustida ishlaganda tun bilan ishlab chiqaman.",
    collocations: ["burn the midnight oil for", "constantly burning the midnight oil", "had to burn the midnight oil"],
    difficulty: "intermediate",
    category: "Work & Study"
  },
  {
    phrase: "Hit the nail on the head",
    meaning: "Biror narsani to'g'ri va aniq aytish yoki bajarish.",
    uzbekEquivalent: "Mil boshiga urmoq / To'g'ri ta'riflash.",
    example: "You hit the nail on the head when you said the project needed more planning.",
    exampleTranslation: "Loyiha ko'proq rejalashtirish kerakligini aytganingizda, to'g'ri ta'rifladingiz.",
    speakingIdea: "My teacher hit the nail on the head when she explained why I kept making the same mistake.",
    speakingIdeaTranslation: "O'qituvchim nima uchun bir xil xatoni takrorlab kelayotganimni tushuntirganda, to'g'ri ta'rifladi.",
    collocations: ["really hit the nail on the head", "hit the nail on the head with", "you've hit the nail on the head"],
    difficulty: "intermediate",
    category: "Communication"
  },
  {
    phrase: "Break the ice",
    meaning: "Tanish bo'lmagan odamlar bilan muloqotni boshlash uchun biror qiziqarli narsa qilish.",
    uzbekEquivalent: "Muloqotni osonlashtirish / Ko'ngilni ochish.",
    example: "He told a funny joke to break the ice at the beginning of the meeting.",
    exampleTranslation: "U yig'ilish boshida muloqotni osonlashtirish uchun kulgili hazil aytdi.",
    speakingIdea: "When I meet new people, I usually ask about their hobbies to break the ice.",
    speakingIdeaTranslation: "Yangi odamlar bilan tanishganda, odatda muloqotni boshlash uchun ularning qiziqishlari haqida so'rayman.",
    collocations: ["break the ice with", "something to break the ice", "tried to break the ice"],
    difficulty: "beginner",
    category: "Social"
  },
  {
    phrase: "Bite the bullet",
    meaning: "Qiyin yoki og'riqli vaziyatni sabr bilan qabul qilish.",
    uzbekEquivalent: "Tishingni tishingga qo'y / Azobga chida.",
    example: "I hate going to the dentist, but I decided to bite the bullet and make an appointment.",
    exampleTranslation: "Men tish shifokoriga borishni yoqtirmayman, lekin azobga chidam va qabulga yozdirdim.",
    speakingIdea: "Sometimes you just have to bite the bullet and do the things you've been avoiding.",
    speakingIdeaTranslation: "Ba'zida shunchaki azobga chidab, qochib yurgan narsalarni qilish kerak bo'ladi.",
    collocations: ["just bite the bullet", "had to bite the bullet", "bite the bullet and do"],
    difficulty: "intermediate",
    category: "Attitude"
  },
  {
    phrase: "Under the weather",
    meaning: "Kasal yoki yomon his qilish.",
    uzbekEquivalent: "Kasalroq bo'lish / Ahvoli yaxshi emas.",
    example: "I'm feeling a bit under the weather today, so I might stay home.",
    exampleTranslation: "Bugun o'zimni yaxshi his qilmayapman, shuning uchun uyda qolishim mumkin.",
    speakingIdea: "When I'm under the weather, I like to drink hot tea and rest all day.",
    speakingIdeaTranslation: "Ahvolim yaxshi bo'lmaganda, issiq choy ichib, kun bo'yi dam olishni yaxshi ko'raman.",
    collocations: ["feeling under the weather", "a bit under the weather", "still under the weather"],
    difficulty: "beginner",
    category: "Health"
  },
  {
    phrase: "Spill the beans",
    meaning: "Yashirin sirni yoki ma'lumotni beixtiyor oshkor qilish.",
    uzbekEquivalent: "Sirni fosh qilish / Og'zingdan chiqarib yuborish.",
    example: "Don't spill the beans about the surprise party — it's a secret!",
    exampleTranslation: "Kutilmagan ziyofat haqida hech kimga aytma — bu sir!",
    speakingIdea: "I accidentally spilled the beans about my friend's promotion before she could announce it herself.",
    speakingIdeaTranslation: "Do'stimning ko'tarilishi haqida u o'zi e'lon qilishidan oldin tasodifan aytib qo'ydim.",
    collocations: ["spill the beans about", "accidentally spilled the beans", "don't spill the beans"],
    difficulty: "beginner",
    category: "Communication"
  },
  {
    phrase: "The ball is in your court",
    meaning: "Qaror qabul qilish navbati sizda.",
    uzbekEquivalent: "Qaror sening qo'lingda / Navbat senda.",
    example: "I've made my offer — the ball is in your court now.",
    exampleTranslation: "Men taklifimni bildirdim — endi qaror sening qo'lingda.",
    speakingIdea: "After I sent the job application, the ball was in their court to decide.",
    speakingIdeaTranslation: "Ish arzonini yuborgandan keyin, qaror qilish ularning navbati edi.",
    collocations: ["the ball is in your court now", "left the ball in their court", "ball is in your court to decide"],
    difficulty: "intermediate",
    category: "Decision Making"
  },
  {
    phrase: "Once in a blue moon",
    meaning: "Juda kamdan-kam hollarda, deyarli hech qachon.",
    uzbekEquivalent: "Kamdan-kam / Nadir holda.",
    example: "We only get snow in this city once in a blue moon.",
    exampleTranslation: "Bu shaharda qor juda kamdan-kam yog'adi.",
    speakingIdea: "Once in a blue moon, I treat myself to an expensive restaurant dinner.",
    speakingIdeaTranslation: "Kamdan-kam hollarda o'zimni qimmat restoranda kechki ovqat bilan siylaman.",
    collocations: ["once in a blue moon", "happens once in a blue moon", "only once in a blue moon"],
    difficulty: "beginner",
    category: "Time & Frequency"
  },
  {
    phrase: "Bite off more than you can chew",
    meaning: "O'z imkoniyatidan ko'ra ko'proq ish olish.",
    uzbekEquivalent: "Ko'zingni og'zingga qarab och.",
    example: "He bit off more than he could chew by taking three jobs at the same time.",
    exampleTranslation: "U bir vaqtning o'zida uchta ish olish bilan o'z imkoniyatidan ko'proq ish olib qo'ydi.",
    speakingIdea: "I bit off more than I could chew when I agreed to help organize the whole conference alone.",
    speakingIdeaTranslation: "Butun konferentsiyani yolg'iz uyushtirish uchun rozi bo'lganimda, o'z imkoniyatimdan ko'proq ish olib qo'ydim.",
    collocations: ["bit off more than I could chew", "don't bite off more than", "risk biting off more than"],
    difficulty: "intermediate",
    category: "Work & Study"
  },
  {
    phrase: "Hit the ground running",
    meaning: "Biror ishni boshida energiya va samaradorlik bilan boshlash.",
    uzbekEquivalent: "Birdaniga tez va samarali ishga kirishish.",
    example: "The new manager hit the ground running and solved several issues on her first day.",
    exampleTranslation: "Yangi menejer birinchi kunidayoq bir necha muammoni hal qilib, samarali ishga kirdi.",
    speakingIdea: "I want to hit the ground running with my new language learning routine.",
    speakingIdeaTranslation: "Yangi til o'rganish tartibimni tez va samarali boshlashni xohlayman.",
    collocations: ["hit the ground running with", "really hit the ground running", "need to hit the ground running"],
    difficulty: "advanced",
    category: "Work & Study"
  },
  {
    phrase: "Let the cat out of the bag",
    meaning: "Yashirin sirni tasodifan oshkor qilish.",
    uzbekEquivalent: "Sirni fosh etib qo'yish.",
    example: "She let the cat out of the bag when she mentioned the surprise birthday party.",
    exampleTranslation: "U kutilmagan tug'ilgan kun ziyofatini tilga olganda sirni fosh etib qo'ydi.",
    speakingIdea: "I almost let the cat out of the bag about the gift we were planning.",
    speakingIdeaTranslation: "Rejalashtirayotgan sovg'amiz haqida sirni deyarli oshkor qilib qo'ydim.",
    collocations: ["let the cat out of the bag about", "accidentally let the cat out", "nearly let the cat out of the bag"],
    difficulty: "beginner",
    category: "Communication"
  },
  {
    phrase: "Throw in the towel",
    meaning: "Biror narsadan voz kechish yoki taslim bo'lish.",
    uzbekEquivalent: "Taslim bo'lish / Qo'l siltash.",
    example: "After years of trying, he finally threw in the towel and changed careers.",
    exampleTranslation: "Yillab harakat qilganidan so'ng, u nihoyat taslim bo'lib, kasb almashtirdi.",
    speakingIdea: "No matter how hard it gets, I refuse to throw in the towel on my dreams.",
    speakingIdeaTranslation: "Qanchalik qiyin bo'lmasin, orzularimdan voz kechishdan bosh tortaman.",
    collocations: ["throw in the towel on", "ready to throw in the towel", "refuse to throw in the towel"],
    difficulty: "intermediate",
    category: "Attitude"
  },
  {
    phrase: "See eye to eye",
    meaning: "Biror masalada kimdir bilan to'liq kelishish.",
    uzbekEquivalent: "Ko'z ko'zga tushmoq / Bir fikrda bo'lmoq.",
    example: "We don't always see eye to eye, but we respect each other's opinions.",
    exampleTranslation: "Biz har doim ham bir fikrda bo'lmaymiz, lekin bir-birimizning fikrlarimizga hurmat qilamiz.",
    speakingIdea: "My brother and I rarely see eye to eye on political topics.",
    speakingIdeaTranslation: "Akam bilan men siyosiy masalalarda kamdan-kam hollarda bir fikrda bo'lamiz.",
    collocations: ["see eye to eye on", "rarely see eye to eye", "don't see eye to eye"],
    difficulty: "beginner",
    category: "Relationships"
  },
  {
    phrase: "Barking up the wrong tree",
    meaning: "Noto'g'ri yo'nalishda izlash yoki noto'g'ri odamni aybdor deb hisoblash.",
    uzbekEquivalent: "Noto'g'ri joydan izlamoq.",
    example: "If you think I took your notebook, you're barking up the wrong tree.",
    exampleTranslation: "Agar daftaringizni men olgan deb o'ylasangiz, noto'g'ri joydan izlayapsiz.",
    speakingIdea: "The police were barking up the wrong tree when they first investigated the case.",
    speakingIdeaTranslation: "Politsiya dastlab ishni tekshirganda noto'g'ri yo'nalishda izladi.",
    collocations: ["barking up the wrong tree", "you're barking up the wrong tree", "were barking up the wrong tree"],
    difficulty: "advanced",
    category: "Problem Solving"
  },
  {
    phrase: "Cost an arm and a leg",
    meaning: "Juda qimmat bo'lish.",
    uzbekEquivalent: "Juda qimmat turmoq / Ko'z chiqarmoq.",
    example: "That new smartphone costs an arm and a leg, but everyone wants one.",
    exampleTranslation: "O'sha yangi smartfon juda qimmat, lekin hamma uni xohlaydi.",
    speakingIdea: "Traveling to Europe cost me an arm and a leg, but it was worth every penny.",
    speakingIdeaTranslation: "Evropaga sayohat qilish juda qimmga tushdi, lekin har bir tiyiniga arzidi.",
    collocations: ["cost an arm and a leg", "costs an arm and a leg", "it cost me an arm and a leg"],
    difficulty: "beginner",
    category: "Money"
  }
];
